# Generated by Django 4.2.26 on 2025-11-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Foto del auto'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=20, verbose_name='Placas'),
        ),
    ]
